services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-detection-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: bot-detection-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: